"""Bitmap helpers for drawing 16x32 digits on the LCD."""

# Each entry maps to an 8x16 character pattern using doubled pixels (2x scaling).
DIGITS = {
    "0": (
        " XXXXX  ",
        "XX   XX ",
        "XX  XXX ",
        "XX X XX ",
        "XXX  XX ",
        "XX   XX ",
        " XXXXX  ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ),
    "1": (
        "   XX   ",
        "  XXX   ",
        "   XX   ",
        "   XX   ",
        "   XX   ",
        "   XX   ",
        " XXXXXX ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ),
    "2": (
        " XXXXX  ",
        "XX   XX ",
        "     XX ",
        "    XX  ",
        "   XX   ",
        "  XX    ",
        "XXXXXXX ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ),
    "3": (
        "XXXXXX  ",
        "     XX ",
        "    XX  ",
        "  XXXX  ",
        "     XX ",
        "     XX ",
        "XXXXXX  ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ),
    "4": (
        "   XXX  ",
        "  XXXX  ",
        " XX XX  ",
        "XX  XX  ",
        "XXXXXXX ",
        "    XX  ",
        "    XX  ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ),
    "5": (
        "XXXXXXX ",
        "XX      ",
        "XXXXX   ",
        "    XX  ",
        "     XX ",
        "XX   XX ",
        " XXXXX  ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ),
    "6": (
        "  XXXX  ",
        " XX     ",
        "XX      ",
        "XXXXXX  ",
        "XX   XX ",
        "XX   XX ",
        " XXXXX  ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ),
    "7": (
        "XXXXXXX ",
        "     XX ",
        "    XX  ",
        "   XX   ",
        "  XX    ",
        "  XX    ",
        "  XX    ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ),
    "8": (
        " XXXXX  ",
        "XX   XX ",
        "XX   XX ",
        " XXXXX  ",
        "XX   XX ",
        "XX   XX ",
        " XXXXX  ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ),
    "9": (
        " XXXXX  ",
        "XX   XX ",
        "XX   XX ",
        " XXXXXX ",
        "     XX ",
        "    XX  ",
        " XXXX   ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ),
}


def draw_digit(display, ch, x, y, color=1):
    pattern = DIGITS.get(ch, DIGITS["0"])
    for row, line in enumerate(pattern):
        for col, pixel in enumerate(line):
            if pixel != " ":
                px = x + col * 2
                py = y + row * 2
                display.pixel(px, py, color)
                display.pixel(px + 1, py, color)
                display.pixel(px, py + 1, color)
                display.pixel(px + 1, py + 1, color)
